### ISSUE TITLE
What is the datapack file structure?

### ISSUE THREAD

**Issue by MinecraftGuy926** [Hantonik/AnvilAPI#31]
### Feature description:

Not seeing where the jsons need to go in the datapack on the wiki. Could you specify how to properly add them, please?

**Comment by zebz213** [comment]
If you figure it out, please post here. I've tried several different ways folder structures and cannot get it to work.

**Comment by BIG-Viljo** [comment]
The path to an anvil recipe in a datapack is as follows `data/your_namespace/recipes/your_anvil_recipe.json`, where `your_namespace` is any namespace of your choice (even `minecraft` I believe).

**Comment by MinecraftGuy926** [comment]
Cheers
